### ISSUE TITLE
provide releases for non-Go developers

### ISSUE THREAD

**Issue by klauern** [augmentable-dev/askgit#10]
It would be nice to release this as a downloadable set of binaries.  I have had some experience with [GoReleaser](https://goreleaser.com/) and I have to say it's a pretty nice little tool, especially if you're working in Go.  I'd prefer to be able to just `brew install gitqlite`, which GoReleaser has good support for: https://goreleaser.com/customization/homebrew/

**Comment by Vialeon** [comment]
Unfortunately GoReleaser does not work with CGO which is necessary for accessing the git objects. This seems to be something that is common throughout pre-built go binary builders as I know xgo also has issues compiling projects with CGO. If you happen to know of a different releaser that doesn't have the aforementioned issue @patrickdevivo and I would love to hear about it

**Comment by jeshan** [comment]
Have you considered AWS Codebuild? You should be able to access git objects in there.

I'm not sure about Go specifics but this example project seems to be using cgo.

https://github.com/shawnxlw/go-k8s-cicd

At line 13 we can read:
https://github.com/shawnxlw/go-k8s-cicd/blob/master/buildspec/build.yml

```
docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e CGO_ENABLED=0 -e GOOS=linux golang:alpine go build -a -installsuffix cgo -o main -v .
```

**Comment by Vialeon** [comment]
If you look under releases I uploaded tar.gz files for linux and OS x86-64 binaries(compiled in xgo) yesterday. 

No homebrew yet.

**Comment by patrickdevivo** [comment]
#50 adds some instructions to the README on how to install via `homebrew`, which will now be maintained. Running via Docker has also been documented, as such I'll close this out as PR #50 merges
