### ISSUE TITLE
Parsing SQL

### ISSUE THREAD

**Issue by pjebs** [augmentable-dev/askgit#32]
I was wondering where in the repo is the SQL getting parsed? How is it being parse?

**Comment by Vialeon** [comment]
For the construction of the SQL database look in the pkg/gitqlite directory specifically the column function that is in most of the git_%.go files. 
What is happening for the construction is the use of a vtab cursor. This is the page documenting that https://www.sqlite.org/c3ref/vtab_cursor.html

For the actual query look from line 120 onward in cmd/root.go
