### ISSUE TITLE
Issues with repository directories with special characters

### ISSUE THREAD

**Issue by nhinds** [augmentable-dev/askgit#41]
`askgit` has trouble with repository directories that contain characters that are either special to Go's `%q` string encoding or special to sqlite. Some characters cause `askgit` to exit with "unrecognized token" trying to create the virtual table, while others make it further and fail (or produce no data) when executing SQL statements.

Some special characters do not render well on github, so I've included equivalent shell commands for making these directories.

The following directories behave the same. `select count(*) from commits` returns no results (not the number 0 - it returns an empty resultset), while `select count(*) from files` panics with "panic: invalid handle":
* `back\slash` (`mkdir 'back\slash'`)
* `thing﷐` (`mkdir 'thing'$'\357\267\220'`)
* `new
line` (`mkdir 'new'$'\n''line'`)
* `doublequotes");--injection` (`mkdir 'doublequotes");--injection'`)

The following directories all fail without running the SQL query, with an error like `unrecognized token: "");"`:
* `quotation"marks` (`mkdir 'quotation"marks'`)
* `comma",separated"` (`mkdir 'comma",separated"'`)

This seems to be caused by building a SQL string using `fmt.Sprintf` and `%q`, which quotes/escapes strings in a way that Go understands rather than in a way that sqlite understands.
Go will format `"` in the middle of a string as `\"`, which Sqlite considers to be a literal backslash character followed by the end of a string, which is why most directories with the double quote character result in "unrecognized token".
For other characters it seems like Go will escape them (e.g. `\` becomes `\\`, newline becomes `\n`), and Sqlite happily passes the escaped versions to the modules' `Create` functions, which presumably try and fail to open a directory named e.g. `back\\slash` instead of `back\slash`

This can be reproduced in the tests by changing the fixture repo from `"repo"` to e.g. `"repo\\"` or `"repo\""`

**Comment by patrickdevivo** [comment]
Hi @nhinds thank you for raising this and for your thoroughness! This is definitely worth addressing and I will investigate a solution soon - I wonder if "serializing" the directory path into a safe string that can be deserialized in the module code makes sense here

**Comment by spoco2** [comment]
Would this also be causing the issue of when running `docker run -v `pwd`:/repo:ro askgit "SELECT * FROM commits"`on a repo with `-` in the title you get `repository does not exist`?

Because this has driven me insane, and I just tried one of our few repositories that do not have a hyphen in the name, and it worked.

**Comment by nhinds** [comment]
I don't think it's the exact same issue -- in the `docker run` example, the repository directory is always `/repo` inside the container, so the `askgit` binary never sees special characters in the directory name. Testing with a repository in `/tmp/git-test/hy-phens` works fine as well, so hyphens don't seem to trigger this in the same way.

Also tested `docker run -v `pwd`:/repo:ro augmentable/askgit "SELECT * FROM commits"` and `docker run -v /tmp/git-test/hy-phens:/repo:ro augmentable/askgit "SELECT * FROM commits"`, which both show the commits fine for me.

**Comment by Vialeon** [comment]
If you run askgit inside of the working directory of the repo such that it is using `os.Getwd()` instead of a user inputted string do you run into the same issue?

**Comment by nhinds** [comment]
Yes, same behaviour when running from the working directory.

`askgit` doesn't use `os.Getwd()` unless you pass something like `--repo=""`, since the `--repo` parameter defaults to ".". All 3 versions (not passing `--repo` so it uses ".", passing `--repo /full/path` so it uses "/full/path", and passing `--repo=""` so it uses `os.Getwd()`) have the same errors when run on these directories.
