### ISSUE TITLE
Incorrect/incomplete install instructions

### ISSUE THREAD

**Issue by federico-razzoli** [augmentable-dev/askgit#49]
$ go get -v -tags=sqlite_vtable github.com/augmentable-dev/askgit
go/src/github.com/go-git/go-git/remote.go:9:2: code in directory /home/federico/go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"

**Comment by patrickdevivo** [comment]
This appears to be a duplicate of #37
